import Atasan from '@/components/Atasan'
import Footer from '@/components/Footer'
import Kepsek from '@/components/Kepsek'
import Navbar from '@/components/Navbar'
import Stuktur from '@/components/StukturSekolah'
import React from 'react'
import Head from 'next/head'

export default function Struktur() {
  return (
    <div>
        <Head>
        <title>Struktur Sekolah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
        <Navbar />
        <Stuktur/>
        <Kepsek />
        <Atasan />
        <Footer />
    </div>
  )
}
