import Footer from '@/components/Footer'
import Headppdb from '@/components/Headppdb'
import Navbar from '@/components/Navbar'
import React from 'react'
import Head from 'next/head'

export default function InformasiPPDB() {
  return (
    <>
    <Head>
        <title>Informasi PPDB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
    <div>
        <Navbar/>
        <Headppdb />
        <Footer />
    </div>
    </>
  )
}
