import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Movie from '@/components/Movie'
import Navbar from '@/components/Navbar'
import React from 'react'
import Head from 'next/head'

export default function TentangSekolah() {
  return (
    <div>
      <Head>
        <title>Tentang Sekolah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
        <Navbar />
        <Header />
        <Movie />
        <Footer />
    </div>
  )
}
