import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import React from 'react'
import Head from 'next/head'

export default function kontak() {
  return (
    <div>
        <Head>
        <title>Kontak Sekolah</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
        <Navbar />
        <Footer />
    </div>
  )
}
