import Corousel from '@/components/Corousel'
import Footer from '@/components/Footer'
import Kejuaraan from '@/components/Kejuaraan'
import Kepsek from '@/components/Kepsek'
import Navbar from '@/components/Navbar'
import Slider from '@/components/Slider'
import Head from 'next/head'



export default function Home() {
  return (
    <>
      <Head>
        <title>HOME | SMEA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <div>
        <Navbar />
        <Slider />
        <Kejuaraan/>
        <Kepsek />
        <Corousel/>
        <Footer />
        
      </div>
      
    </>
  )
}